### PR TITLE
fix(toc): fix inaccurate headerLinkTop calculation

### PR DESCRIPTION
**Pull request by Fedomn**
fix inaccurate headerLinkTop calculation that result in activeTocIndex drift.

### CODE REVIEW

**Comment by Fedomn** [comment]
hi dillonzq, any update about this PR?

**Comment by dillonzq** [comment]
Hi, @Fedomn Thanks for your PR!
Your commitment is fine. And I have added a few improvements to merge it.

But I'm considering changing the way of adjusting the target for the fixed header.
Since the dummy target is tricky, I think about using CSS styles only, whose compatibility is better.

**Comment by Fedomn** [comment]
Hi dillonzq, thank you for your reply.
You are right, it makes more sense to use CSS.

Thank you for your contribution!

**Comment by dillonzq** [comment]
Hi, @Fedomn
The header has been improved in #73 .

**Comment by Fedomn** [comment]
brilliant!

**Pull request merged**
