### PR TITLE
fix(path): broken tag/category link when containing a dot

### PR DESCRIPTION
**Pull request by wtchangdm**
Hi, thank you for this great theme! I noticed an issue that certain tags (like `Node.js`) at footer disappear somehow.

After some investigations, it looks like the same problem as this: https://github.com/gcushen/hugo-academic/commit/4ed72d85b2ed13917b851a642165bf57b6b59852

I've confirmed that this fixes the issue and other tags are still working fine.

### CODE REVIEW

**Comment by wtchangdm** [comment]
Turns out category links have the same problem. I think that's all?

**Comment by dillonzq** [comment]
@wtchangdm That's all. Thanks.
This problem should only appear where `GetPage` is used.

**Comment by dillonzq** [comment]
Hi, @wtchangdm 
When handling East Asia words, such as Chinese, `urlize` will encode them, which causes `.Site.GetPage` to fail.

There is a discussion on the Hugo forum:
https://discourse.gohugo.io/t/how-decode-urls-in-hugo/7549

And there seems to be a perfect solution for East Asia words and dots.

I make it a partial in `function/path.html`.

**Comment by wtchangdm** [comment]
OK, I understand, thanks for the effort!

Dillon <notifications@github.com> 於 2020年5月18日 週一 17:29 寫道：

**Pull request merged**
