### PR TITLE
feat(giscus): the most powerful comment plugin

### PR DESCRIPTION
**Pull request by xwi88**
Online demo for my blog:

- https://xwi88.com/hugo-plugin-giscus-support/

Useful links:

- https://giscus.app
-  https://giscus.app/zh-CN

feat done：  @LeeeSe

### CODE REVIEW

**Comment by dillonzq** [comment]
@xwi88 Thanks for your contribution! But the following problems need to be fixed:

1. When it comes to `src/js/theme.js` changes, you need to run `npm build` locally to generate new `assets/js/theme.js` file and then git add/commit the new file. (I'll add contribution guidelines with this later.)
2. In order to maintain the uniformity of configuration files, it is recommended that new configuration items use the small camel case naming convention. For example, `repo_id` -> `repoId`, `reactions_enabled` -> `reactionsEnabled`. (I'll also add contribution guidelines with this later.)
3. Some configuration items are not needed and can be removed. For example, `crossorigin` is useless.
4. It is recommended to synchronize the change of the configuration file to exampleSite doc file `exampleSite/content/posts/theme-documentation-basics/index.en.md` and `exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md`. (I'll add contribution guidelines with this later.)

**Comment by dillonzq** [comment]
> @xwi88 Thanks for your contribution! But the following problems need to be fixed:
> 
> 1. When it comes to `src/js/theme.js` changes, you need to run `npm build` locally to generate new `assets/js/theme.js` file and then git add/commit the new file. (I'll add contribution guidelines with this later.)
> 2. In order to maintain the uniformity of configuration files, it is recommended that new configuration items use the small camel case naming convention. For example, `repo_id` -> `repoId`, `reactions_enabled` -> `reactionsEnabled`. (I'll also add contribution guidelines with this later.)
> 3. Some configuration items are not needed and can be removed. For example, `crossorigin` is useless.
> 4. It is recommended to synchronize the change of the configuration file to exampleSite doc file `exampleSite/content/posts/theme-documentation-basics/index.en.md` and `exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md`. (I'll add contribution guidelines with this later.)

I have fixed these in [61eccb2](https://github.com/dillonzq/LoveIt/pull/664/commits/61eccb2502064ee628d6e1983af9020ed6d1de57) and [ea043a](https://github.com/dillonzq/LoveIt/pull/664/commits/ea043a2674faa7e2b310e66bf9ae8e4b98be5859).

**Comment by xwi88** [comment]
So sorry for the commit with word spell and assets. Thks your fixes and deal again.

One suggestion: the file `assets/js/theme.js`, maybe  auto build with **github pipelines**, reduce the diffs for all contributors.

**Comment by dillonzq** [comment]
@xwi88 Thanks for your advice.  I would consider introducing github pipelines.

**Pull request merged**
